package dmg.expensebook.utils

const val PREFS_FILENAME = "EXPENSE_BOOK_PREFS_FILENAME"

const val INTENT_FILTER_ADD_NEW_BOOK_PAGE = "INTENT_FILTER_ADD_NEW_BOOK_PAGE"
const val FIRST_TIME_OPEN_APP_KEY = "FIRST_TIME_OPEN_APP_KEY"
